BEGIN;
DELETE FROM "account_emailaddress";
DELETE FROM "p_library_publisher";
DELETE FROM "auth_user_groups";
DELETE FROM "django_content_type";
DELETE FROM "account_emailconfirmation";
DELETE FROM "p_library_userprofile";
DELETE FROM "p_library_author";
DELETE FROM "django_admin_log";
DELETE FROM "socialaccount_socialapp";
DELETE FROM "socialaccount_socialtoken";
DELETE FROM "auth_permission";
DELETE FROM "auth_group";
DELETE FROM "p_library_book";
DELETE FROM "auth_user_user_permissions";
DELETE FROM "p_library_friend";
DELETE FROM "django_site";
DELETE FROM "socialaccount_socialapp_sites";
DELETE FROM "socialaccount_socialaccount";
DELETE FROM "auth_group_permissions";
DELETE FROM "django_session";
DELETE FROM "auth_user";
COMMIT;
