# Generated by Django 2.2.6 on 2020-07-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0009_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.IntegerField(blank=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Неопределен'), (1, 'Мужской'), (2, 'Женский')], default=0, verbose_name='Пол'),
        ),
    ]
